### PR TITLE
binding active account to the `cluster-admin` role in GKE

### LINKED ISSUE #24: Kubeapps up fails in a default GKE cluster
Steps to reproduce:

1. Build a default GKE cluster with `gcloud container clusters create my-cluster`
2. Run ./kubeapps up

You get the following error:

```
ERRO[0009] Error updating clusterroles kubeless-controller-deployer: clusterroles.rbac.authorization.k8s.io "kubeless-controller-deployer" is forbidden: attempt to grant extra privileges: [PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["services"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["create"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["get"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["update"]} PolicyRule{Resources:["configmaps"], APIGroups:[""], Verbs:["patch"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["apps"], Verbs:["patch"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["create"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["get"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["delete"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["list"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["update"]} PolicyRule{Resources:["deployments"], APIGroups:["extensions"], Verbs:["patch"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["list"]} PolicyRule{Resources:["pods"], APIGroups:[""], Verbs:["delete"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["get"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["list"]} PolicyRule{Resources:["functions"], APIGroups:["k8s.io"], Verbs:["watch"]}] user=&{apulido@gmail.com  [system:authenticated] map[]} ownerrules=[PolicyRule{Resources:["selfsubjectaccessreviews"], APIGroups:["authorization.k8s.io"], Verbs:["create"]} PolicyRule{NonResourceURLs:["/api" "/api/*" "/apis" "/apis/*" "/healthz" "/swaggerapi" "/swaggerapi/*" "/version"], Verbs:["get"]}] ruleResolutionErrors=[]
```

### PR DESCRIPTION
**Pull request by ngtuna**
This PR fixes the permission issue #24 on GKE when the active account doesn't have cluster admin permission to create ClusterRole. Cluster environment detection (gke, aws, minikube, etc) might be implemented in further PR. In this PR's scope, I introduce `--cloud-provider` flag which is defaulting to `gke`. So in case of GKE, an additional ClusterRoleBinding object that maps the active account to `cluster-admin` role will be added to the installation.

Requirements: 

- the active account must be allowed to create RoleBinding/ClusterRoleBinding
- the above ClusterRoleBinding needs to be created before other ClusterRole/Role in the installation (double check on kubecfg cc/ @anguslees)

fix #24

### CODE REVIEW

File: cmd/down.go [hunk 1]
```diff
@@ -33,6 +39,17 @@ var downCmd = &cobra.Command{
 		if err != nil {
 			return err
 		}
+
+		// k8s on GKE
+		crb := &unstructured.Unstructured{}
```
Comment (andresmgot) [inline cmd/down.go]: you can define this inside the `if` block

File: cmd/root.go [hunk 2]
```diff
@@ -50,6 +50,7 @@ Find more information at https://github.com/kubeapps/installer.`,
 func init() {
 	RootCmd.PersistentFlags().CountP("verbose", "v", "Increase verbosity.")
 	RootCmd.PersistentFlags().Set("logtostderr", "true")
+	RootCmd.PersistentFlags().String("cloud-provider", "gke", "Specify the cloud provider.")
```
Comment (andresmgot) [inline cmd/root.go]: in my opinion:
 - This flag should be a choice selection (the allowed values would be `gke` and `minikube`
 - The default value should be empty
 - If there is not auto detection this flag should be mandatory

File: pkg/gke/gke.go [hunk 3]
```diff
@@ -0,0 +1,127 @@
...
+	"os/user"
+	"path/filepath"
+	"runtime"
+	"strings"
+
+	"k8s.io/apimachinery/pkg/apis/meta/v1/unstructured"
+)
+
+func BuildCrbObject() (*unstructured.Unstructured, error) {
+	user, err := getActiveUser()
```
Comment (andresmgot) [inline pkg/gke/gke.go]: the user should be a parameter, that way the function is more easily testable

File: pkg/gke/gke.go [hunk 4]
```diff
@@ -0,0 +1,127 @@
...
+	if err != nil {
+		return "", err
+	}
+	configPath := filepath.Join(gcloudPath, "configurations")
+	f, err := os.Open(filepath.Join(configPath, "config_"+string(activeConfig)))
+	if err != nil {
+		return "", err
+	}
+	defer f.Close()
+	ini, err := parseINI(f)
```
Comment (andresmgot) [inline pkg/gke/gke.go]: maybe we don't need to reinvent the wheel:
https://github.com/go-ini/ini

File: pkg/gke/gke.go [hunk 5]
```diff
@@ -0,0 +1,127 @@
...
+	}
+	active, ok := core["account"]
+	if !ok {
+		return "", err
+	}
+
+	return active, nil
+}
+
+func parseINI(ini io.Reader) (map[string]map[string]string, error) {
```
Comment (andresmgot) [inline pkg/gke/gke.go]: if we do this, we need to add tests

File: pkg/gke/gke.go (hunk 4 above)
Comment (ngtuna) [reply pkg/gke/gke.go]: Ah cool. I haven't known it

File: cmd/root.go (hunk 2 above)
Comment (ngtuna) [reply cmd/root.go]: I think `--cloud_provider` really means k8s running on cloud. I haven't had chance to test the installer on aws or other _popular_ clouds. I am not sure if we have to do any special action on aws like we do on gke (granting that special permission), so we support the flag there for further _switch cases_. Minikube should not be listed on this flag (or if it does, we should call `--cloud-provider=none`)

File: pkg/gke/gke.go (hunk 3 above)
Comment (ngtuna) [reply pkg/gke/gke.go]: That function is quite strait-forward to just forming the clusterrolebinding with most fields are fixed. `user` is the only custom field, so I don't think we need unit-test for it. The `getActiveUser()` would need tests

File: cmd/root.go (hunk 2 above)
Comment (andresmgot) [reply cmd/root.go]: yeah, I was thinking in changing the flag name or `--cloud-provider=none` seems fine as well. In any case I think it should be a choice parameter (`--cloud-provider=google` would do nothing but it will be allowed).

BTW, what happens if in minikube you try to add the cluster role binding?

Comment (ngtuna) [reply cmd/root.go]: Interesting... On minikube it's still being created without issues. But we won't want to do that. So choices:

1) `--cloud-provider` default to `none` then on minikube just run `kubeapps up`, on gke `kubeapps up --cloud-provider=gke`
2)`--cloud-provider` default to `gke` then on gke just run `kubeapps up`, on minikube run `kubeapps up --cloud-provider=none` 
3) default to empty. I don't think we should go with this -> longer typing for user.

File: pkg/gke/gke.go (hunk 3 above)
Comment (andresmgot) [reply pkg/gke/gke.go]: Well, we need to test this in two different ways:

 - Assume that the content of this CRB object can change and the software will still work. In this case we would need to cover this with integration tests.
 - Ensure that (only) the current definition works: that way you need to ensure that if someone changes it, he should know what he is doing and modify the unit test that cover this to the new format.

As far as I know we are not going to add integration tests for GKE (at least for the moment) so with a unit test at least you ensure that no ones modify it by accident. 

In any case, I am okay with not adding now a unit test now for this, but if in the future we discover a bug here and we want to add a unit test, it will be easier if the `getActiveUser` is outside this function.

File: cmd/root.go (hunk 2 above)
Comment (andresmgot) [reply cmd/root.go]: For this case I think we should go for the longer typing. If I am in GKE and I forgot to use the `--cloud-provider=gke` I would need to figure it out why the deployment is failing. Or defaulting to`gke` since using the CRB in minikube is not critical?

Comment (ngtuna) [reply cmd/root.go]: Forget about that flag for now. I would do a simple detection based on the k8s version convention on gke: 

```
$ gcloud container get-server-config
...
validMasterVersions:
- 1.8.3-gke.0
- 1.8.2-gke.0
- 1.8.1-gke.1
- 1.7.10-gke.0
- 1.7.9-gke.0
- 1.7.8-gke.0
- 1.6.11-gke.0
```

If there is something changes in the way gke labeling k8s version in future, we can always update the installer.

File: pkg/gke/gke.go (hunk 4 above)
Comment (ngtuna) [reply pkg/gke/gke.go]: imported that lib. Thanks @andresmgot

**Comment by ngtuna** [comment]
@andresmgot I updated PR to tackle on your comments. Please take a look

File: pkg/gke/testsdkconfig/failure/active_config [hunk 6]
```diff
@@ -0,0 +1 @@
+test
```
Comment (andresmgot) [inline pkg/gke/testsdkconfig/failure/active_config]: better to write these simple files in the tests they are being used: it is more maintainable to define the files there, if not you don't know which file is related to which test.

Comment (ngtuna) [reply pkg/gke/testsdkconfig/failure/active_config]: I intended to do that way, but I changed my mind because: the project contains a very small number of files and keep those separate files reduces the coding cost as well as increases visibility: Each folder test contains set of files for that test, not a single file. I am also happy to embed those into code. So I vote 0 for this (in the sense of -1, 0, 1 in voting) :p. Right now I just land the PR, we can do it in a separate PR if we want :p
